// Regenerates src/roots/amd/index.ts from the PEM files next to it (downloaded from
// https://kdsintf.amd.com/vcek/v1/<Product>/cert_chain: ASK then ARK). Embedding
// the PEM text as TS keeps the package importable everywhere (Workers, browsers,
// bun) without text-import loaders.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const dir = new URL("../src/roots/amd/", import.meta.url).pathname;
const files = readdirSync(dir).filter((f) => f.endsWith(".pem")).sort();
let out = "// GENERATED by scripts/gen-roots.ts from the sibling *.pem files. Do not edit.\n";
out += "// Each entry is the AMD KDS cert_chain for a product line: [ASK, ARK] in PEM.\n";
out += "export const AMD_CERT_CHAINS: Record<string, string> = {\n";
for (const f of files) {
  const name = f.replace(/\.pem$/, "");
  const product = name[0]!.toUpperCase() + name.slice(1);
  out += `  ${JSON.stringify(product)}: ${JSON.stringify(readFileSync(join(dir, f), "utf8"))},\n`;
}
out += "};\n";
writeFileSync(join(dir, "index.ts"), out);
console.log("wrote", join(dir, "index.ts"), files);
