// Signs golden/golden.src.json and golden/models.src.json with the OFFLINE root
// (~/.gpubnb/root-signing.json: { kid, alg, pub, priv } b64u) and writes the
// signed blobs golden/golden.json and golden/models.json. Usage:
//   bun scripts/sign-golden.ts [--key path] [--issued-at <unix>]
// The src files are the human-edited truth; the signed blobs are what ships.
import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { b64u, DOMAINS, ROOTS, GoldenSetSchema, ModelCatalogSchema, signBlob, verifyGolden, verifyModels, simulatedMeasurement, hex, bytesEqual, ed25519PublicKey } from "../src/index.ts";

const args = process.argv.slice(2);
const argOf = (name: string) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : undefined; };
const keyPath = argOf("--key") ?? join(homedir(), ".gpubnb", "root-signing.json");
const issuedAt = argOf("--issued-at") ? Number(argOf("--issued-at")) : Math.floor(Date.now() / 1000);
const dir = new URL("../golden/", import.meta.url).pathname;

const key = JSON.parse(readFileSync(keyPath, "utf8")) as { kid: string; alg: string; pub: string; priv: string };
if (key.kid !== ROOTS.OFFLINE_ROOT_KID) throw new Error(`key kid ${key.kid} != pinned ${ROOTS.OFFLINE_ROOT_KID}`);
const priv = b64u.decode(key.priv);
if (!bytesEqual(ed25519PublicKey(priv), ROOTS.OFFLINE_ROOT_PUB)) throw new Error("key file public half does not match the pinned offline root");

// golden
const goldenSrc = JSON.parse(readFileSync(join(dir, "golden.src.json"), "utf8")) as Record<string, unknown>;
const strip = (o: Record<string, unknown>) => Object.fromEntries(Object.entries(o).filter(([k]) => !k.startsWith("_")));
const golden = GoldenSetSchema.parse({ ...strip(goldenSrc), issued_at: issuedAt });
for (const e of golden.entries) {
  if (e.simulated) {
    const want = hex.encode(await simulatedMeasurement(e.runner_version));
    if (e.measurement !== want) throw new Error(`simulated entry ${e.runner_version}: measurement must be SHA384("gpubnb-simulated-${e.runner_version}") = ${want}`);
  }
}
const goldenBlob = await signBlob(golden, priv, DOMAINS.golden, ROOTS.OFFLINE_ROOT_KID);
await verifyGolden(goldenBlob);
writeFileSync(join(dir, "golden.json"), JSON.stringify(goldenBlob, null, 2) + "\n");

// models
const modelsSrc = JSON.parse(readFileSync(join(dir, "models.src.json"), "utf8")) as Record<string, unknown>;
const models = ModelCatalogSchema.parse({ ...strip(modelsSrc), issued_at: issuedAt });
const modelsBlob = await signBlob(models, priv, DOMAINS.models, ROOTS.OFFLINE_ROOT_KID);
await verifyModels(modelsBlob);
writeFileSync(join(dir, "models.json"), JSON.stringify(modelsBlob, null, 2) + "\n");

// embed as TS so consumers (Workers, browsers, bun) need no JSON loader
const srcDir = new URL("../src/", import.meta.url).pathname;
writeFileSync(join(srcDir, "golden.ts"),
  "// GENERATED by scripts/sign-golden.ts. Signed by the offline root; verify with verifyGolden()/verifyModels().\n" +
  "import type { SignedBlob } from \"./signed.ts\";\n" +
  `export const GOLDEN_BLOB: SignedBlob = ${JSON.stringify(goldenBlob)};\n` +
  `export const MODELS_BLOB: SignedBlob = ${JSON.stringify(modelsBlob)};\n`);

console.log(`signed golden (${golden.entries.length} entries) and models (${models.entries.length} entries) at issued_at=${issuedAt}`);
