// Renders every wrangler.template.jsonc into a sibling wrangler.jsonc
// (gitignored) and writes stack.generated.json at the repo root for
// build-time consumers (Astro configs, static pages). Run after cloning and
// after changing stack.config.jsonc / stack.local.jsonc:
//
//   bun run configure
//
// Template tokens:
//   __BASE_DOMAIN__    -> baseDomain (e.g. proc.io)
//   __AUTH_ENDPOINT__  -> resolved AuthGravity origin
//   __D1:<key>__       -> d1[<key>]; if unset, the whole line is dropped so
//                         wrangler provisions a fresh database on deploy

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { Glob } from 'bun';
import { loadStack, repoRoot } from './stack';

const cfg = loadStack();

const BANNER =
  '// GENERATED by `bun run configure` from wrangler.template.jsonc — do not\n' +
  '// edit this file; edit the template (or stack.local.jsonc) and re-run.\n';

function render(template: string): string {
  const lines = template
    .replaceAll('__BASE_DOMAIN__', cfg.baseDomain)
    .replaceAll('__AUTH_ENDPOINT__', cfg.authEndpoint)
    .split('\n')
    .filter((line) => {
      const m = line.match(/__D1:([\w-]+)__/);
      return !(m && !cfg.d1[m[1]!]);
    })
    .map((line) => line.replace(/__D1:([\w-]+)__/, (_, key) => cfg.d1[key]!));
  return BANNER + lines.join('\n');
}

const glob = new Glob('**/wrangler.template.jsonc');
const written: string[] = [];
for (const match of glob.scanSync({ cwd: repoRoot })) {
  if (match.includes('node_modules/')) continue;
  const templatePath = join(repoRoot, match);
  const outPath = join(dirname(templatePath), 'wrangler.jsonc');
  writeFileSync(outPath, render(readFileSync(templatePath, 'utf8')));
  written.push(relative(repoRoot, outPath));
}

writeFileSync(
  join(repoRoot, 'stack.generated.json'),
  JSON.stringify({ baseDomain: cfg.baseDomain, authEndpoint: cfg.authEndpoint }, null, 2) + '\n',
);

console.log(`stack: baseDomain=${cfg.baseDomain} authEndpoint=${cfg.authEndpoint}`);
for (const f of written.sort()) console.log(`wrote ${f}`);
console.log('wrote stack.generated.json');
