// The single choke point for every external command clusterpilot runs.
//
// Two gates live here, and they are deliberately separate:
//
//   assertReadOnly     the default. Known binary, known read-only subcommand,
//                      no mutating verb anywhere in the argv. Everything the
//                      model can reach goes through this one.
//
//   assertMutation     only reachable from the executor, only when the caller
//                      passes `mutating: true`, and only for the handful of
//                      upgrade operations clusterpilot knows how to drive and
//                      verify. Destructive verbs are refused here too: there
//                      is no path through this file to `reset`, `wipe`,
//                      `delete`, or `apply-config`.
//
// The model never reaches the second gate. Its `probe` tool calls run() without
// `mutating`, so a model that decides an upgrade should happen still cannot
// start one; commands are generated by src/plan.ts and run by src/execute.ts.

import { spawn } from "node:child_process";

/** Read-only subcommands, per binary. Anything not listed is refused. */
const ALLOWED: Record<string, Set<string>> = {
  talosctl: new Set([
    "version",
    "get",
    "list",
    "read",
    "services",
    "service",
    "health",
    "dmesg",
    "disks",
    "memory",
    "containers",
    "stats",
    "config",
    "time",
  ]),
  kubectl: new Set([
    "get",
    "describe",
    "version",
    "top",
    "logs",
    "api-resources",
    "api-versions",
    "cluster-info",
    "explain",
    "config",
    "auth",
  ]),
  // `repo` only ever touches the local chart cache, never the cluster.
  helm: new Set([
    "list",
    "ls",
    "get",
    "history",
    "status",
    "search",
    "show",
    "repo",
    "version",
    "env",
  ]),
};

/**
 * Verbs that mutate. Checked against every argument, not just the subcommand,
 * so a mutating verb buried in a longer argv has nowhere to hide. `update` is
 * absent from the list on purpose: the only command that reaches it is
 * `helm repo update`, which refreshes the local chart cache.
 */
const DENIED = new Set([
  "apply",
  "create",
  "delete",
  "edit",
  "patch",
  "replace",
  "scale",
  "drain",
  "cordon",
  "uncordon",
  "taint",
  "annotate",
  "label",
  "exec",
  "attach",
  "cp",
  "port-forward",
  "proxy",
  "run",
  "expose",
  "rollout",
  "upgrade",
  "upgrade-k8s",
  "install",
  "uninstall",
  "rollback",
  "reset",
  "reboot",
  "shutdown",
  "apply-config",
  "bootstrap",
  "etcd",
  "push",
  "wipe",
  "gen",
]);

/**
 * The complete set of mutations clusterpilot can perform, keyed by the first
 * two argv tokens after the binary's flags. Nothing else is executable, no
 * matter who asks.
 *
 * Note what is absent: there is no way to reach `talosctl reset`, `wipe`,
 * `apply-config`, `kubectl delete`, or `helm uninstall`. Those are recovery and
 * teardown operations that want a human who can see the machine, and a plan
 * step that quietly performed one would be far worse than a plan step that
 * stops and asks.
 */
const MUTATIONS: { bin: string; sub: string; second?: string; label: string }[] = [
  { bin: "talosctl", sub: "upgrade", label: "upgrade Talos on a node (reboots it)" },
  { bin: "talosctl", sub: "upgrade-k8s", label: "upgrade Kubernetes control plane and kubelet" },
  { bin: "talosctl", sub: "etcd", second: "snapshot", label: "take an etcd snapshot" },
  { bin: "helm", sub: "upgrade", label: "upgrade a Helm release" },
  { bin: "helm", sub: "rollback", label: "roll a Helm release back" },
  { bin: "kubectl", sub: "rollout", label: "restart or watch a rollout" },
];

/** Verbs no gate will ever pass, including the mutation gate. */
const NEVER = new Set([
  "reset",
  "wipe",
  "apply-config",
  "bootstrap",
  "delete",
  "uninstall",
  "shutdown",
  "reboot",
  "gen",
]);

/**
 * Git operations the sync step may perform, in a repo it is pointed at.
 *
 * `push` is absent deliberately. Sync records what the cluster is into a local
 * commit; publishing that is a human's call, and a tool that pushed on its own
 * would be making a decision about a shared branch nobody asked it to make.
 * `reset`, `clean`, `checkout`, and `rebase` are absent for the obvious reason:
 * they can destroy uncommitted work in a repo clusterpilot does not own.
 */
const GIT_ALLOWED = new Set(["add", "commit", "status", "rev-parse", "diff", "log", "show"]);

export class GitNotAllowedError extends Error {}

const GIT_NEVER = ["push", "reset", "clean", "checkout", "rebase", "merge", "fetch", "pull"];

export function assertGit(argv: string[]): void {
  if (argv[0]?.split("/").pop() !== "git") {
    throw new GitNotAllowedError("not a git command");
  }

  for (const arg of argv.slice(1)) {
    if (GIT_NEVER.includes(arg)) {
      throw new GitNotAllowedError(`git '${arg}' is never run by clusterpilot`);
    }
  }

  const sub = findSubcommand(argv);
  if (!sub || !GIT_ALLOWED.has(sub)) {
    throw new GitNotAllowedError(
      `git '${sub ?? "?"}' is not allowed; sync may only ${[...GIT_ALLOWED].join(", ")}`,
    );
  }
}

export class MutationNotPlannedError extends Error {}

/**
 * Gate for commands that change the cluster. Verifies the operation is one of
 * the known upgrade mutations and that no absolutely-forbidden verb appears
 * anywhere in the argv.
 */
export function assertMutation(argv: string[]): void {
  if (argv.length === 0) throw new MutationNotPlannedError("empty command");

  const bin = argv[0]!.split("/").pop()!;

  for (const arg of argv.slice(1)) {
    if (NEVER.has(arg)) {
      throw new MutationNotPlannedError(
        `'${arg}' is never executable by clusterpilot; it needs a human at the console`,
      );
    }
  }

  const sub = findSubcommand(argv);
  if (!sub) throw new MutationNotPlannedError(`'${bin}' needs a subcommand`);

  const match = MUTATIONS.find((m) => m.bin === bin && m.sub === sub);
  if (!match) {
    throw new MutationNotPlannedError(
      `'${bin} ${sub}' is not one of the upgrade operations clusterpilot can perform`,
    );
  }

  if (match.second) {
    // `talosctl etcd` alone is broad; only the snapshot subcommand is allowed.
    const rest = argv.slice(argv.indexOf(sub) + 1).filter((a) => !a.startsWith("-"));
    if (rest[0] !== match.second) {
      throw new MutationNotPlannedError(
        `only '${bin} ${sub} ${match.second}' is allowed, not '${bin} ${sub} ${rest[0] ?? ""}'`,
      );
    }
  }
}

/**
 * Global flags that take a separate value. Without these, `talosctl -n proc-0
 * get disks` reads `proc-0` as the subcommand and gets refused.
 */
const VALUE_FLAGS = new Set([
  // git's repo-directory flag, so `git -C /path add` parses `add` as the verb.
  "-C",
  "-n",
  "--nodes",
  "--namespace",
  "-e",
  "--endpoints",
  "--context",
  "--kube-context",
  "--kubeconfig",
  "--talosconfig",
  "-o",
  "--output",
  "--as",
  "--field-selector",
  "-l",
  "--selector",
  "--since",
  "--tail",
]);

/**
 * The subcommand is the first bare word that is neither a flag nor the value of
 * one. `--flag=value` carries its own value, so it never consumes the next arg.
 */
export function findSubcommand(argv: string[]): string | undefined {
  for (let i = 1; i < argv.length; i++) {
    const arg = argv[i]!;
    if (arg.startsWith("-")) {
      if (VALUE_FLAGS.has(arg)) i++;
      continue;
    }
    return arg;
  }
  return undefined;
}

export class RefusedCommandError extends Error {}

export interface RunResult {
  ok: boolean;
  stdout: string;
  stderr: string;
  code: number | null;
  durationMs: number;
  /** True when stdout hit maxBytes. Truncated JSON must never be parsed as if whole. */
  truncated: boolean;
}

export interface RunOptions {
  timeoutMs?: number;
  /**
   * Cap on stdout. The default is generous because `kubectl get pods -A -o json`
   * on a modest cluster is already past a megabyte, and a cap that silently
   * clipped it would turn into a confusing JSON parse error downstream.
   */
  maxBytes?: number;
  /**
   * Route through the mutation gate instead of the read-only one. Only
   * src/execute.ts sets this, and only for steps src/plan.ts generated. Callers
   * that omit it -- including every model-facing path -- get the read-only gate.
   */
  mutating?: boolean;
  /** Route through the git gate. Only src/sync.ts sets this. */
  git?: boolean;
  /** Streams output as it arrives, for long operations like a node upgrade. */
  onOutput?: (chunk: string) => void;
}

/** Throws RefusedCommandError unless argv is a read-only command we recognize. */
export function assertReadOnly(argv: string[]): void {
  if (argv.length === 0) throw new RefusedCommandError("empty command");

  const bin = argv[0]!.split("/").pop()!;
  const allowedSubs = ALLOWED[bin];
  if (!allowedSubs) {
    throw new RefusedCommandError(
      `binary '${bin}' is not allowed; clusterpilot only runs ${Object.keys(ALLOWED).join(", ")}`,
    );
  }

  for (const arg of argv.slice(1)) {
    if (DENIED.has(arg)) {
      throw new RefusedCommandError(
        `'${arg}' is a mutating verb; clusterpilot is read-only and plans upgrades rather than applying them`,
      );
    }
  }

  const sub = findSubcommand(argv);
  if (!sub) throw new RefusedCommandError(`'${bin}' needs a subcommand`);
  if (!allowedSubs.has(sub)) {
    throw new RefusedCommandError(
      `'${bin} ${sub}' is not on the read-only allowlist (allowed: ${[...allowedSubs].join(", ")})`,
    );
  }
}

export async function run(argv: string[], opts: RunOptions = {}): Promise<RunResult> {
  if (opts.git) assertGit(argv);
  else if (opts.mutating) assertMutation(argv);
  else assertReadOnly(argv);

  const timeoutMs = opts.timeoutMs ?? 45_000;
  const maxBytes = opts.maxBytes ?? 32 * 1024 * 1024;
  const started = Date.now();

  return await new Promise<RunResult>((resolve) => {
    const child = spawn(argv[0]!, argv.slice(1), {
      stdio: ["ignore", "pipe", "pipe"],
      env: process.env,
    });

    let stdout = "";
    let stderr = "";
    let settled = false;
    let truncated = false;

    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      finish(null, `timed out after ${timeoutMs}ms`);
    }, timeoutMs);

    const finish = (code: number | null, extraErr?: string) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({
        ok: code === 0,
        stdout,
        stderr: extraErr ? `${stderr}${extraErr}` : stderr,
        code,
        durationMs: Date.now() - started,
        truncated,
      });
    };

    child.stdout.on("data", (chunk: Buffer) => {
      const text = chunk.toString("utf8");
      opts.onOutput?.(text);
      if (stdout.length < maxBytes) stdout += text;
      else truncated = true;
    });
    child.stderr.on("data", (chunk: Buffer) => {
      const text = chunk.toString("utf8");
      // talosctl reports upgrade progress on stderr, so it streams too.
      opts.onOutput?.(text);
      if (stderr.length < maxBytes) stderr += text;
    });
    child.on("error", (err) => finish(null, err.message));
    child.on("close", (code) => finish(code));
  });
}

/** Runs a command and parses stdout as JSON, returning undefined on any failure. */
export async function runJson<T>(argv: string[], opts?: RunOptions): Promise<T | undefined> {
  const res = await run(argv, opts);
  if (!res.ok) return undefined;
  try {
    return JSON.parse(res.stdout) as T;
  } catch {
    return undefined;
  }
}
