// Shared shapes for the inventory the probes collect, the upstream versions we
// look up, and the findings the deterministic analyzer derives from the two.

export type Severity = "critical" | "warning" | "info";

/** One read-only command we ran, kept so the plan can cite its evidence. */
export interface ProbeResult {
  /** Stable key, e.g. "talos.version" or "k8s.nodes". */
  id: string;
  /** The exact argv we ran, so a human can reproduce it. */
  command: string[];
  ok: boolean;
  /** Parsed value when ok, otherwise undefined. */
  data?: unknown;
  /** Populated when the command failed or the parse did. */
  error?: string;
  durationMs: number;
}

export interface TalosDisk {
  id: string;
  size: string;
  model?: string;
  serial?: string;
  transport?: string;
  rotational: boolean;
}

export interface TalosNode {
  name: string;
  /** e.g. "1.13.8", absent if the version call failed. */
  version?: string;
  kernel?: string;
  /** Image Factory schematic ID; the upgrade image must be built from this. */
  schematic?: string;
  extensions: { name: string; version: string }[];
  /** Real block devices; loop devices are filtered out. */
  disks: TalosDisk[];
  services: { id: string; state: string; health: string }[];
}

export interface KubeNode {
  name: string;
  /** kubelet version without the leading v, e.g. "1.36.3". */
  kubeletVersion: string;
  roles: string[];
  ready: boolean;
  osImage: string;
  kernel: string;
  containerRuntime: string;
  /** Conditions in a bad state (DiskPressure=True etc). */
  pressures: string[];
}

export interface HelmRelease {
  name: string;
  namespace: string;
  /** Chart name without the version suffix, e.g. "kube-prometheus-stack". */
  chart: string;
  chartVersion: string;
  appVersion: string;
  status: string;
  /**
   * The values the operator actually supplied, as YAML -- `helm get values`,
   * not `--all`. Chart defaults are deliberately excluded: replaying only the
   * explicit overrides onto a new chart is what lets new defaults through,
   * which is the whole point of upgrading.
   */
  userValues?: string;
}

export interface WorkloadHealth {
  /** Pods not Running/Succeeded, capped so the model prompt stays small. */
  unhealthyPods: {
    namespace: string;
    name: string;
    phase: string;
    reason: string;
    restarts: number;
  }[];
  pendingPvcs: { namespace: string; name: string }[];
  /** Warning-type events, deduplicated by reason. */
  recentWarnings: { namespace: string; reason: string; message: string; count: number }[];
}

export interface Inventory {
  collectedAt: string;
  kubeContext: string;
  talosNodes: TalosNode[];
  kubeNodes: KubeNode[];
  helmReleases: HelmRelease[];
  workloads: WorkloadHealth;
  probes: ProbeResult[];
}

export interface UpstreamVersions {
  /** Stable Talos releases, newest first, e.g. ["1.14.1", "1.14.0", ...]. */
  talos: string[];
  /** Stable Kubernetes releases, newest first. */
  kubernetes: string[];
  /** Chart name -> available versions, newest first. */
  charts: Record<string, string[]>;
  errors: string[];
}

export interface Finding {
  id: string;
  severity: Severity;
  category: "talos" | "kubernetes" | "helm" | "hardware" | "workload" | "topology";
  title: string;
  detail: string;
  current?: string;
  latest?: string;
  /** Concrete commands a human would run. Never executed by this tool. */
  suggested?: string[];
}

// ---------------------------------------------------------------------------
// Execution
//
// Everything below describes work clusterpilot can carry out rather than just
// describe. The load-bearing rule is that a Step's argv is generated by
// src/plan.ts from computed findings -- never composed by the model, and never
// accepted as free text. The model reads, watches, and diagnoses; it does not
// get to decide what runs.
// ---------------------------------------------------------------------------

export type StepKind =
  | "snapshot"
  | "talos-upgrade"
  | "k8s-upgrade"
  | "helm-upgrade"
  | "verify";

/** What the runner polls for after a step, and what counts as success. */
export type WatchSpec =
  | {
      /** The node drops off the API and comes back on a new version. */
      kind: "node-reboot";
      node: string;
      expectTalosVersion: string;
      timeoutMs: number;
    }
  | { kind: "k8s-version"; expectVersion: string; timeoutMs: number }
  | { kind: "helm-release"; release: string; namespace: string; expectChartVersion: string; timeoutMs: number }
  /** Wait for workloads to stop churning; no version expectation. */
  | { kind: "settle"; timeoutMs: number };

/**
 * A gate evaluated immediately before a step runs, against freshly collected
 * state rather than the state the plan was built from. Plans can sit for hours
 * between generation and approval.
 */
export type PreflightCheck =
  | { kind: "cluster-healthy" }
  | { kind: "no-crashloops" }
  | { kind: "snapshot-exists"; path: string }
  /** The installer image must carry the schematic the node is actually running. */
  | { kind: "schematic-matches"; node: string; schematic: string }
  | { kind: "talos-version-is"; node: string; version: string }
  | { kind: "k8s-version-is"; version: string };

export interface Step {
  id: string;
  title: string;
  kind: StepKind;
  /** The exact command. Generated by plan.ts; the executor runs this verbatim. */
  argv: string[];
  /** Plain-language statement of what this does to the cluster. */
  effect: string;
  downtime: "none" | "brief" | "full-outage";
  preflight: PreflightCheck[];
  watch?: WatchSpec;
  /** Commands that prove the step landed. Read-only. */
  verify: string[][];
}

export interface ExecutionPlan {
  createdAt: string;
  context: string;
  steps: Step[];
}

export type StepStatus = "pending" | "running" | "succeeded" | "failed" | "skipped" | "aborted";

export interface StepOutcome {
  stepId: string;
  status: StepStatus;
  startedAt: string;
  finishedAt?: string;
  /** Combined stdout/stderr, capped. */
  output?: string;
  error?: string;
  /** Model diagnosis, when a step failed and the troubleshooter ran. */
  diagnosis?: Diagnosis;
}

export interface Diagnosis {
  summary: string;
  likelyCause: string;
  /** Whether the cluster is believed to be in a stable state right now. */
  clusterStable: boolean;
  /** Suggested next actions for a human. Never executed automatically. */
  recommendations: string[];
}

