// Embeds the binary fixtures as base64 into fixtures.generated.ts, because
// workers-pool tests cannot read files from disk at runtime. Run by generate.sh.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const b64 = (name: string): string => readFileSync(join(dir, name)).toString('base64');
const text = (name: string): string => readFileSync(join(dir, name), 'utf8').trim();

const expectedOids = text('expected-oids.txt').split('\n').filter(Boolean).sort();

const out = `// GENERATED by test/fixtures/generate.sh — do not edit by hand.
export const REF_DELTA_PACK_B64 = '${b64('ref-delta.pack')}';
export const OFS_DELTA_PACK_B64 = '${b64('ofs-delta.pack')}';
export const EXPECTED_OIDS: string[] = ${JSON.stringify(expectedOids, null, 2)};
export const A_TXT_OID = '${text('a-txt-oid.txt')}';
export const A_TXT_CONTENT = 'hello\\nworld\\n';
`;
writeFileSync(join(dir, 'fixtures.generated.ts'), out);
console.log(`embedded ${expectedOids.length} oids`);
